### ISSUE TITLE
Freezing when installing songs with a large library

### ISSUE THREAD

**Issue by Dylan-Brotherston** [dotMortis/beat-saver-client#42]
As the number of installed songs increases the time taken to scan the library becomes longer.
This is of course unavoidable, but the frequency that the library is scanned could be reduced to alleviate this issue.

Currently whenever a new song is installed the library has to be re-scanned, this makes it next to impossible to install many song simultaneously as you keep getting interrupted by scanning.

I can think of 3 solution:
1) scan in a different thread
2) separate the downloading and installing of songs, so that installing can be done in bulk after the user has finished searching for songs
3) Installing a song should, theoretically, modify the library in a known way. There should , theoretically, not be a need to scan as the new state is just the old state plus the new song.

**Comment by dotMortis** [comment]
@Dylan-Brotherston  Hey! Thanks for the feedback, I would need a little more information.
Does this problem occur only during the bulk installation or also when you click on the direct installation?

And what number of songs are we talking about?

**Comment by Dylan-Brotherston** [comment]
Sorry, " bulk installation" was the wrong phrasing to use in this case.

using the integrated beatsaver search interface and using the direct install button will cause beat-saver-client to download the song and immediately install it, after the install is done it will then immediately scan all installed songs.

This means that if I am trying to install multiple songs, or scrolling/searching for now songs the interface will freeze until the scan is complete.

At one point, after being a little over eager and installing all bestsaber playlist i have about 2000 songs, that took ~5 seconds per scan. with 500 songs currently (probably still way to many to ever play) its about a 2 second freeze every scan.

**Comment by dotMortis** [comment]
Nice to get some early feedback on this behavior.
I figured there might be a performance issue here. But the problem should not be the scan, but the refresh of the GUI. 
The actual scan just creates a hash of all the folders and checks it against the hash of the database entries.

After that each songcard fetches the song information from a map object again and that should be the problem.

I will test both checks again and optimize the code.

**Comment by Dylan-Brotherston** [comment]
Thank for that quick response.
If you need any more information or apparently my ability to provide a stress test let me know.

**Comment by dotMortis** [comment]
It's actually a bug and a poor design decision 👎 
Hotfix will coming in about 2h.

**Comment by dotMortis** [comment]
https://github.com/dotMortis/beat-saver-client/releases/tag/v0.8.4-beta

The initial sync is still a big pain, but after that it should be usable even with 2k songs.

@Dylan-Brotherston Just restart the client and the update should download.
Feedback for the patch would be really great :)

**Comment by Dylan-Brotherston** [comment]
@dotMortis great work.
Massive performance upgrade. No freezing at all with 2000 songs.
